microserviceName: "inventory"

strategy:
  type: Recreate
  rollingUpdate: null

image:
  repository: acrpfpos.azurecr.io/play.inventory
  tag : 1.0.0

envVariables:
  ServiceSettings__Authority: https://gameplayeconomy.com/identity-svc
  ASPNETCORE_URLS: "http://0.0.0.0:5004"

container:
  port: 5004

resources:
  requests:
    memory: "150Mi"
    cpu: "20m"
  limits:
    memory: "180Mi"
    cpu: "100m"

identityClientId: b96b2764-330d-4616-b8c7-1705acb8f0c3
    